const { body, validationResult } = require("express-validator");
const { AppError } = require("../utils/errorHandler");

const validateJob = [
  // Base fields (no prefix)
  body("job_uuid").notEmpty().withMessage("job_uuid is required"),
  body("sm8_account_uuid").notEmpty().withMessage("sm8_account_uuid is required"),
  body("generated_job_id").optional().isString(),
  body("notes").optional().isString(),

  // ─── Discovery (q_discovery_) ──────────────────────────────
  body("q_discovery_what_after").optional().isString(),
  body("q_discovery_diff_app").optional().isIn(["Yes", "No"]),
  body("q_discovery_diff_app_details").optional().isString(),
  body("q_discovery_special_integration").optional().isIn(["Yes", "No"]),
  body("q_discovery_integration_requirements").optional().isString(),
  body("q_discovery_has_website").optional().isIn(["Yes", "No"]),
  body("q_discovery_website_address").optional().isURL().withMessage("Must be a valid URL"),
  body("q_discovery_website_form_link").optional().isIn(["Yes", "No"]),
  body("q_discovery_devices").optional().isArray().withMessage("Devices must be an array"),
  body("q_discovery_staff_android").optional().isIn(["Yes", "No"]),
  body("q_discovery_android_limitation").optional().isIn(["Yes", "No"]),
  body("q_discovery_accounting").optional().isIn(["Yes", "No"]),
  body("q_discovery_accounting_package").optional().isIn(["Xero", "MYOB", "Quickbooks", "Other"]),
  body("q_discovery_accounting_other_warning").optional().isIn(["Yes", "No"]),
  body("q_discovery_accounting_myob_warning").optional().isIn(["Yes", "No"]),
  body("q_discovery_avg_jobs").optional().isInt({ min: 0 }).withMessage("Must be a positive integer"),
  body("q_discovery_templates").optional().isIn(["Invoice", "Quote", "Both","N/A"]),
  body("q_discovery_checklist").optional().isIn(["Yes", "No"]),
  body("q_discovery_checklist_examples").optional().isIn(["Yes", "No"]),
  body("q_discovery_forms").optional().isIn(["Yes", "No"]),
  body("q_discovery_forms_examples").optional().isIn(["Yes", "No"]),
  body("q_discovery_special_features").optional().isArray().withMessage("Special features must be an array"),
  body("q_discovery_plan").optional().isIn(["Starter - $29", "Growing - $79", "Premium - $149", "Premium Plus - $349"]),
  body("q_discovery_explained_plans").optional().isIn(["Yes", "No"]),
  body("q_discovery_plan_notes").optional().isString(),
  body("q_discovery_training").optional().isIn(["Google meet", "Ellenbrook", "Client Premises", "Other"]),
  body("q_discovery_other_notes").optional().isString(),

  // ─── Project Management (q_pm_) ────────────────────────────
  body("q_pm_directors_declaration").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_pm_xero_agreement_sent").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_pm_create_client_folder").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_pm_upload_setup_google_sheet").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_pm_upload_logo_client_folder").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_pm_send_project_kickoff_email").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_pm_plan_chosen").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_pm_account_created").optional().isIn(["Yes", "No"]),
  body("q_pm_account_owners_login_details").optional().isString(),
  body("q_pm_technical_discovery_call_setup").optional().isIn(["Yes", "No"]),
  body("q_pm_warranty_setup").optional().isIn(["Yes", "No"]),
  body("q_pm_sales_timesheet_added").optional().isIn(["Yes", "No", "N/A"]),
  body("q_pm_google_review_sent").optional().isIn(["Yes", "No", "N/A"]),
  body("q_pm_google_review_received").optional().isIn(["Yes", "No", "N/A"]),
  body("q_pm_training_session_organised").optional().isIn(["Yes", "No", "N/A"]),
  body("q_pm_training_session_notes").optional().isString(),
  body("q_pm_rebate_applied_for").optional().isIn(["Yes", "No", "N/A"]),
  body("q_pm_rebate_applied_email_sent").optional().isIn(["Yes", "No", "N/A"]),
  body("q_pm_rebate_approved_email_sent").optional().isIn(["Yes", "No", "N/A"]),
  body("q_pm_invoicing_initial_sent").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_pm_invoicing_initial_paid").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_pm_invoicing_progressive_sent").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_pm_invoicing_progressive_paid").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_pm_invoicing_final_sent").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_pm_invoicing_final_paid").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_pm_invoicing_notes").optional().isString(),
  body("q_pm_refresher_call_organised").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_pm_refresher_call_notes").optional().isString(),

  // ─── Designs (q_designs_) ──────────────────────────────────
  body("q_designs_ask_old_invoice").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_designs_ask_terms").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_designs_send_designer_info").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_designs_send_proposals").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_designs_client_chosen").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_designs_upload_headers").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_designs_upload_chosen").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_designs_templates_created").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_designs_templates_sent").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_designs_templates_uploaded").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_designs_more_notes").optional().isString(),

  // ─── Settings (q_settings_) ────────────────────────────────
  body("q_settings_upload_logo").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_company_info").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_tax_settings").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_email_settings").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_tasks").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_region_languages").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_notification").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_job_settings").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_invoicing").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_job_settings2").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_public_holiday").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_staff_leave").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_sm8_14").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_staff_accounts").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_labour_rates").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_security_roles").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_categories").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_create_queues").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_admin_invoice").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_admin_reschedule").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_notes").optional().isString(),

  // ─── Settings Add‑Ons (also q_settings_) ──────────────────
  body("q_settings_automation").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_customer_feedback").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_feedback_google_link").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_recurring_jobs").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_simple_enquiry_form").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_track_my_arrival").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_badges").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_job_templates").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_job_allocations").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_partial_invoicing").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_forms").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_assets").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_deputy").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_mailchimp").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_servicem8_network").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_external_calendars").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_calendar_import").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_two_way_email").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_advance_reporting_pack").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_self_serve_online_booking").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_services").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_margin_billing").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_job_costing").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_proposals").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_servicem8_phone").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_client_sites").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_bundles").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_settings_addon_more_notes").optional().isString(),

  // ─── Templates (q_templates_) ──────────────────────────────
  body("q_templates_parts_ordered_template").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_request_payment_template").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_sms_invoice").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_sms_quote").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_tech_delayed_template").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_sms_more_notes").optional().isString(),
  body("q_templates_overdue_payment_template").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_payment_demand_template").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_standard_invoice_template").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_standard_quote_template").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_customer_feedback").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_email_more_notes").optional().isString(),
  body("q_templates_copy_invoice_template_from_default").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_create_invoice_based_on_quote").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_update_default_invoice_preferences").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_add_bank_details").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_add_discount_material").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_create_work_order_based_on_quote").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_payment_followup_3_times").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_payment_followup_2_days_before").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_payment_followup_7_days_after").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_payment_followup_14_days_after").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_payment_update_email_default_3rd_followup").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_payment_update_sms_default_3rd_followup").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_quote_followup_3_times").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_quote_followup_2_days_after").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_quote_followup_7_days_after").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_quote_followup_14_days_after").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_unsuccessful_after_30_days").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_update_booking_confirmation_email_text").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_templates_update_booking_reminder_email_text").optional().isIn(["In Progress", "Completed", "N/A"]),

  // ─── Accounts (q_accounts_) ────────────────────────────────
  body("q_accounts_xero_integrated").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_accounts_myob_integrated").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_accounts_quickbooks_integrated").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_accounts_stripe_account_created").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_accounts_servicem8_pay_installed").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_accounts_xero_email_sent").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_accounts_xero_account_code_created").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_accounts_servicem8_pay_settings_checked").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_accounts_client_list_provided").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_accounts_client_list_uploaded").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_accounts_price_list_provided").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_accounts_price_list_uploaded").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_accounts_data_import_notes").optional().isString(),
  body("q_accounts_more_notes").optional().isString(),

  // ─── Forms (q_forms_) ──────────────────────────────────────
  body("q_forms_jsa_rebranded").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_forms_swms_rebranded").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_forms_service_report_rebranded").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_forms_jsa_added").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_forms_swms_added").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_forms_service_report_added").optional().isIn(["In Progress", "Completed", "N/A"]),
  body("q_forms_more_notes").optional().isString(),

  // Final check
  (req, res, next) => {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      const error = new AppError("Validation failed", 400, errors.array());
      return next(error);
    }
    next();
  },
];

module.exports = validateJob;